# Generated by Django 5.1.6 on 2025-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emailform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailform',
            name='subject',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
