# Generated by Django 5.1.6 on 2025-03-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_emailform_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailform',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='emailform',
            name='subject',
            field=models.TextField(blank=True, default='No subject', max_length=50),
        ),
    ]
